[configuration]
server_port = 5901
auto_resume = false
sound_source = "BlackHole 2ch-"
sound_source_index = 0
log_level = "INFO"
ssdp_interval_mins = 10.0
auto_reconnect = false
lpcm_stream_size = "U64maxNotChunked"
wav_stream_size = "U32maxNotChunked"
rf64_stream_size = "U64maxNotChunked"
flac_stream_size = "NoneChunked"
bits_per_sample = 16
streaming_format = "Wav"
monitor_rms = false
capture_timeout = 2000
inject_silence = false
buffering_delay_msec = 0
active_renderers = []
hidden_renderers = []
last_network = "192.168.0.91"
config_dir = "/Users/jjbastida/.swyh-rs"
config_id = "_cli"
read_only = false
color_theme = 8
widget_scheme = 1
language = "en-US"
use_dither = true
